apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: demo-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
