apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: kube-deploy
servers: 1
agents: 1
kubeAPI:
  host: 127.0.0.1
  hostIP: 127.0.0.1
  hostPort: "6445"
image: rancher/k3s:v1.36.5-k3s1@sha256:057cfd5a9d51b89f1f0ee139c28d5d5fdd5aa7ddeac2742a0ba90c6dbc0329bb
ports:
  - port: 127.0.0.1:8080:80
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: 5m
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --secrets-encryption
        nodeFilters:
          - server:0
      - arg: --secrets-encryption-provider=secretbox
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
